homepage: "https://github.com/libass/libass"
main_repo: "https://github.com/libass/libass"
language: c
primary_contact: "chortos@inbox.lv"
auto_ccs:
  - "greg@kinoho.net"
  - "rcombs@rcombs.me"
  - "vabnick@gmail.com"
architectures:
  - x86_64
  - i386
sanitizers:
  - address
  - memory
  - undefined
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
coverage_extra_args: >
  -ignore-filename-regex=libass/subprojects/.*
  -ignore-filename-regex=libass/build/subprojects/.*
